/** Pure MCP-OAuth constants + helpers (no I/O). See ADR 0004. */

export const MCP_SCOPE = "community:read";
export const OFFLINE_SCOPE = "offline_access";
export const MCP_SCOPES = [MCP_SCOPE, OFFLINE_SCOPE] as const;

/** Access-token claim carrying the org picked at consent (consent `referenceId`). */
export const ORG_CLAIM = "org_id";

export const ACCESS_TOKEN_TTL_SECONDS = 60 * 60;
export const REFRESH_TOKEN_TTL_SECONDS = 30 * 24 * 60 * 60;
/** A rotated refresh token may be replayed for this long (retried refresh). */
export const REFRESH_TOKEN_REUSE_SECONDS = 30;

export const OAUTH_RATE_LIMITS = {
	register: { window: 60 * 60, max: 5 },
	token: { window: 60, max: 30 },
	authorize: { window: 60, max: 30 },
} as const;

export const MCP_PATH = "/api/mcp";
export const OAUTH_SELECT_ORG_PATH = "/oauth/select-org";
export const OAUTH_CONSENT_PATH = "/oauth/consent";

export function mcpResourceUrl(origin: string): string {
	return `${origin.replace(/\/+$/, "")}${MCP_PATH}`;
}

/**
 * CIMD client ids are https URLs (same rule as `cimdUrlRejection`); DCR ids are opaque strings generated by us, so a DCR client
 * can never present a URL id.
 */
export type RegistrationKind = "cimd" | "dcr";

export function registrationKind(clientId: string): RegistrationKind {
	return /^https:\/\//i.test(clientId) ? "cimd" : "dcr";
}

/**
 * The picker is always shown, but better-auth re-runs `postLogin.shouldRedirect` when the page
 * calls `/oauth2/continue`. A short-lived per-session marker, written when the member picks an
 * org, tells that second pass to let the flow through.
 */
export const ORG_PICK_TTL_MS = 2 * 60 * 1000;

export const orgPickIdentifier = (sessionId: string) => `oauth-org-picked:${sessionId}`;

export function isOrgPickValid(
	marker: { value: string; expiresAt: number } | null,
	activeOrganizationId: string | null | undefined,
	now: number
): boolean {
	if (!marker || !activeOrganizationId) return false;
	return marker.expiresAt > now && marker.value === activeOrganizationId;
}

/** Where `/oauth2/continue` / `/oauth2/consent` want the browser to go next (client callback or a page). */
export function oauthRedirectUrl(result: unknown): string | null {
	if (typeof result !== "object" || result === null) return null;
	const r = result as { url?: unknown; redirect_uri?: unknown };
	for (const v of [r.url, r.redirect_uri]) if (typeof v === "string" && v) return v;
	return null;
}

const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "[::1]"]);

/**
 * DCR clients usually omit `application_type`, which OIDC defaults to `web` and which rejects
 * http loopback / private-use redirects. Desktop MCP clients (Inspector, Claude Code, Cursor)
 * register exactly those, so infer `native` when no redirect needs the web rules. Validation of
 * the URIs themselves stays with the plugin.
 */
export function inferApplicationType(redirectUris: readonly string[]): "native" | undefined {
	if (redirectUris.length === 0) return undefined;
	for (const raw of redirectUris) {
		const url = URL.parse(raw);
		if (!url) return undefined;
		if (url.protocol === "https:") return undefined;
		if (url.protocol === "http:" && !LOOPBACK_HOSTS.has(url.hostname)) return undefined;
	}
	return "native";
}
