/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedCommunityRouteImport } from './routes/_authed/_community'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedOnboardingSuccessRouteRouteImport } from './routes/_authed/onboarding/success/route'
import { Route as AuthedOnboardingInvitationsRouteRouteImport } from './routes/_authed/onboarding/invitations/route'
import { Route as AuthedOnboardingCreateRouteRouteImport } from './routes/_authed/onboarding/create/route'
import { Route as AuthedCommunityMemoriesRouteRouteImport } from './routes/_authed/_community/memories/route'
import { Route as AuthedCommunityMembersRouteRouteImport } from './routes/_authed/_community/members/route'
import { Route as AuthedCommunityDashboardRouteRouteImport } from './routes/_authed/_community/dashboard/route'
import { Route as AuthedCommunityCommunityTreeRouteRouteImport } from './routes/_authed/_community/community-tree/route'
import { Route as AuthedCommunitySettingsOverviewRouteRouteImport } from './routes/_authed/_community/settings/overview/route'
import { Route as AuthedCommunitySettingsMembersRouteRouteImport } from './routes/_authed/_community/settings/members/route'
import { Route as AuthedCommunitySettingsFieldsRouteRouteImport } from './routes/_authed/_community/settings/fields/route'
import { Route as AuthedCommunityProfileRelationshipsRouteRouteImport } from './routes/_authed/_community/profile/relationships/route'
import { Route as AuthedCommunityProfileInfoRouteRouteImport } from './routes/_authed/_community/profile/info/route'
import { Route as AuthedCommunityProfileAddressesRouteRouteImport } from './routes/_authed/_community/profile/addresses/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCommunityRoute = AuthedCommunityRouteImport.update({
  id: '/_community',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingSuccessRouteRoute =
  AuthedOnboardingSuccessRouteRouteImport.update({
    id: '/onboarding/success',
    path: '/onboarding/success',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOnboardingInvitationsRouteRoute =
  AuthedOnboardingInvitationsRouteRouteImport.update({
    id: '/onboarding/invitations',
    path: '/onboarding/invitations',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOnboardingCreateRouteRoute =
  AuthedOnboardingCreateRouteRouteImport.update({
    id: '/onboarding/create',
    path: '/onboarding/create',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCommunityMemoriesRouteRoute =
  AuthedCommunityMemoriesRouteRouteImport.update({
    id: '/memories',
    path: '/memories',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunityMembersRouteRoute =
  AuthedCommunityMembersRouteRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunityDashboardRouteRoute =
  AuthedCommunityDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunityCommunityTreeRouteRoute =
  AuthedCommunityCommunityTreeRouteRouteImport.update({
    id: '/community-tree',
    path: '/community-tree',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunitySettingsOverviewRouteRoute =
  AuthedCommunitySettingsOverviewRouteRouteImport.update({
    id: '/settings/overview',
    path: '/settings/overview',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunitySettingsMembersRouteRoute =
  AuthedCommunitySettingsMembersRouteRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunitySettingsFieldsRouteRoute =
  AuthedCommunitySettingsFieldsRouteRouteImport.update({
    id: '/settings/fields',
    path: '/settings/fields',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunityProfileRelationshipsRouteRoute =
  AuthedCommunityProfileRelationshipsRouteRouteImport.update({
    id: '/profile/relationships',
    path: '/profile/relationships',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunityProfileInfoRouteRoute =
  AuthedCommunityProfileInfoRouteRouteImport.update({
    id: '/profile/info',
    path: '/profile/info',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)
const AuthedCommunityProfileAddressesRouteRoute =
  AuthedCommunityProfileAddressesRouteRouteImport.update({
    id: '/profile/addresses',
    path: '/profile/addresses',
    getParentRoute: () => AuthedCommunityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/community-tree': typeof AuthedCommunityCommunityTreeRouteRoute
  '/dashboard': typeof AuthedCommunityDashboardRouteRoute
  '/members': typeof AuthedCommunityMembersRouteRoute
  '/memories': typeof AuthedCommunityMemoriesRouteRoute
  '/onboarding/create': typeof AuthedOnboardingCreateRouteRoute
  '/onboarding/invitations': typeof AuthedOnboardingInvitationsRouteRoute
  '/onboarding/success': typeof AuthedOnboardingSuccessRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/addresses': typeof AuthedCommunityProfileAddressesRouteRoute
  '/profile/info': typeof AuthedCommunityProfileInfoRouteRoute
  '/profile/relationships': typeof AuthedCommunityProfileRelationshipsRouteRoute
  '/settings/fields': typeof AuthedCommunitySettingsFieldsRouteRoute
  '/settings/members': typeof AuthedCommunitySettingsMembersRouteRoute
  '/settings/overview': typeof AuthedCommunitySettingsOverviewRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/community-tree': typeof AuthedCommunityCommunityTreeRouteRoute
  '/dashboard': typeof AuthedCommunityDashboardRouteRoute
  '/members': typeof AuthedCommunityMembersRouteRoute
  '/memories': typeof AuthedCommunityMemoriesRouteRoute
  '/onboarding/create': typeof AuthedOnboardingCreateRouteRoute
  '/onboarding/invitations': typeof AuthedOnboardingInvitationsRouteRoute
  '/onboarding/success': typeof AuthedOnboardingSuccessRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/addresses': typeof AuthedCommunityProfileAddressesRouteRoute
  '/profile/info': typeof AuthedCommunityProfileInfoRouteRoute
  '/profile/relationships': typeof AuthedCommunityProfileRelationshipsRouteRoute
  '/settings/fields': typeof AuthedCommunitySettingsFieldsRouteRoute
  '/settings/members': typeof AuthedCommunitySettingsMembersRouteRoute
  '/settings/overview': typeof AuthedCommunitySettingsOverviewRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_community': typeof AuthedCommunityRouteWithChildren
  '/_authed/_community/community-tree': typeof AuthedCommunityCommunityTreeRouteRoute
  '/_authed/_community/dashboard': typeof AuthedCommunityDashboardRouteRoute
  '/_authed/_community/members': typeof AuthedCommunityMembersRouteRoute
  '/_authed/_community/memories': typeof AuthedCommunityMemoriesRouteRoute
  '/_authed/onboarding/create': typeof AuthedOnboardingCreateRouteRoute
  '/_authed/onboarding/invitations': typeof AuthedOnboardingInvitationsRouteRoute
  '/_authed/onboarding/success': typeof AuthedOnboardingSuccessRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/_community/profile/addresses': typeof AuthedCommunityProfileAddressesRouteRoute
  '/_authed/_community/profile/info': typeof AuthedCommunityProfileInfoRouteRoute
  '/_authed/_community/profile/relationships': typeof AuthedCommunityProfileRelationshipsRouteRoute
  '/_authed/_community/settings/fields': typeof AuthedCommunitySettingsFieldsRouteRoute
  '/_authed/_community/settings/members': typeof AuthedCommunitySettingsMembersRouteRoute
  '/_authed/_community/settings/overview': typeof AuthedCommunitySettingsOverviewRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/community-tree'
    | '/dashboard'
    | '/members'
    | '/memories'
    | '/onboarding/create'
    | '/onboarding/invitations'
    | '/onboarding/success'
    | '/api/auth/$'
    | '/profile/addresses'
    | '/profile/info'
    | '/profile/relationships'
    | '/settings/fields'
    | '/settings/members'
    | '/settings/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/community-tree'
    | '/dashboard'
    | '/members'
    | '/memories'
    | '/onboarding/create'
    | '/onboarding/invitations'
    | '/onboarding/success'
    | '/api/auth/$'
    | '/profile/addresses'
    | '/profile/info'
    | '/profile/relationships'
    | '/settings/fields'
    | '/settings/members'
    | '/settings/overview'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/_community'
    | '/_authed/_community/community-tree'
    | '/_authed/_community/dashboard'
    | '/_authed/_community/members'
    | '/_authed/_community/memories'
    | '/_authed/onboarding/create'
    | '/_authed/onboarding/invitations'
    | '/_authed/onboarding/success'
    | '/api/auth/$'
    | '/_authed/_community/profile/addresses'
    | '/_authed/_community/profile/info'
    | '/_authed/_community/profile/relationships'
    | '/_authed/_community/settings/fields'
    | '/_authed/_community/settings/members'
    | '/_authed/_community/settings/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_community': {
      id: '/_authed/_community'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedCommunityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding/success': {
      id: '/_authed/onboarding/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof AuthedOnboardingSuccessRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/invitations': {
      id: '/_authed/onboarding/invitations'
      path: '/onboarding/invitations'
      fullPath: '/onboarding/invitations'
      preLoaderRoute: typeof AuthedOnboardingInvitationsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/create': {
      id: '/_authed/onboarding/create'
      path: '/onboarding/create'
      fullPath: '/onboarding/create'
      preLoaderRoute: typeof AuthedOnboardingCreateRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_community/memories': {
      id: '/_authed/_community/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AuthedCommunityMemoriesRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/members': {
      id: '/_authed/_community/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedCommunityMembersRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/dashboard': {
      id: '/_authed/_community/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedCommunityDashboardRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/community-tree': {
      id: '/_authed/_community/community-tree'
      path: '/community-tree'
      fullPath: '/community-tree'
      preLoaderRoute: typeof AuthedCommunityCommunityTreeRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/settings/overview': {
      id: '/_authed/_community/settings/overview'
      path: '/settings/overview'
      fullPath: '/settings/overview'
      preLoaderRoute: typeof AuthedCommunitySettingsOverviewRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/settings/members': {
      id: '/_authed/_community/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthedCommunitySettingsMembersRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/settings/fields': {
      id: '/_authed/_community/settings/fields'
      path: '/settings/fields'
      fullPath: '/settings/fields'
      preLoaderRoute: typeof AuthedCommunitySettingsFieldsRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/profile/relationships': {
      id: '/_authed/_community/profile/relationships'
      path: '/profile/relationships'
      fullPath: '/profile/relationships'
      preLoaderRoute: typeof AuthedCommunityProfileRelationshipsRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/profile/info': {
      id: '/_authed/_community/profile/info'
      path: '/profile/info'
      fullPath: '/profile/info'
      preLoaderRoute: typeof AuthedCommunityProfileInfoRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
    '/_authed/_community/profile/addresses': {
      id: '/_authed/_community/profile/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof AuthedCommunityProfileAddressesRouteRouteImport
      parentRoute: typeof AuthedCommunityRoute
    }
  }
}

interface AuthedCommunityRouteChildren {
  AuthedCommunityCommunityTreeRouteRoute: typeof AuthedCommunityCommunityTreeRouteRoute
  AuthedCommunityDashboardRouteRoute: typeof AuthedCommunityDashboardRouteRoute
  AuthedCommunityMembersRouteRoute: typeof AuthedCommunityMembersRouteRoute
  AuthedCommunityMemoriesRouteRoute: typeof AuthedCommunityMemoriesRouteRoute
  AuthedCommunityProfileAddressesRouteRoute: typeof AuthedCommunityProfileAddressesRouteRoute
  AuthedCommunityProfileInfoRouteRoute: typeof AuthedCommunityProfileInfoRouteRoute
  AuthedCommunityProfileRelationshipsRouteRoute: typeof AuthedCommunityProfileRelationshipsRouteRoute
  AuthedCommunitySettingsFieldsRouteRoute: typeof AuthedCommunitySettingsFieldsRouteRoute
  AuthedCommunitySettingsMembersRouteRoute: typeof AuthedCommunitySettingsMembersRouteRoute
  AuthedCommunitySettingsOverviewRouteRoute: typeof AuthedCommunitySettingsOverviewRouteRoute
}

const AuthedCommunityRouteChildren: AuthedCommunityRouteChildren = {
  AuthedCommunityCommunityTreeRouteRoute:
    AuthedCommunityCommunityTreeRouteRoute,
  AuthedCommunityDashboardRouteRoute: AuthedCommunityDashboardRouteRoute,
  AuthedCommunityMembersRouteRoute: AuthedCommunityMembersRouteRoute,
  AuthedCommunityMemoriesRouteRoute: AuthedCommunityMemoriesRouteRoute,
  AuthedCommunityProfileAddressesRouteRoute:
    AuthedCommunityProfileAddressesRouteRoute,
  AuthedCommunityProfileInfoRouteRoute: AuthedCommunityProfileInfoRouteRoute,
  AuthedCommunityProfileRelationshipsRouteRoute:
    AuthedCommunityProfileRelationshipsRouteRoute,
  AuthedCommunitySettingsFieldsRouteRoute:
    AuthedCommunitySettingsFieldsRouteRoute,
  AuthedCommunitySettingsMembersRouteRoute:
    AuthedCommunitySettingsMembersRouteRoute,
  AuthedCommunitySettingsOverviewRouteRoute:
    AuthedCommunitySettingsOverviewRouteRoute,
}

const AuthedCommunityRouteWithChildren = AuthedCommunityRoute._addFileChildren(
  AuthedCommunityRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCommunityRoute: typeof AuthedCommunityRouteWithChildren
  AuthedOnboardingCreateRouteRoute: typeof AuthedOnboardingCreateRouteRoute
  AuthedOnboardingInvitationsRouteRoute: typeof AuthedOnboardingInvitationsRouteRoute
  AuthedOnboardingSuccessRouteRoute: typeof AuthedOnboardingSuccessRouteRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCommunityRoute: AuthedCommunityRouteWithChildren,
  AuthedOnboardingCreateRouteRoute: AuthedOnboardingCreateRouteRoute,
  AuthedOnboardingInvitationsRouteRoute: AuthedOnboardingInvitationsRouteRoute,
  AuthedOnboardingSuccessRouteRoute: AuthedOnboardingSuccessRouteRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
