/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTestRouteImport } from './routes/_authed/test'
import { Route as onboardingLoginRouteImport } from './routes/(onboarding)/login'
import { Route as ApiWebhookPolarRouteImport } from './routes/api/webhook/polar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedCommunityPickRouteRouteImport } from './routes/_authed/community/pick/route'
import { Route as onboardingOnboardProfileRouteRouteImport } from './routes/(onboarding)/onboard/profile/route'
import { Route as onboardingOnboardOrganizationRouteRouteImport } from './routes/(onboarding)/onboard/organization/route'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTestRoute = AuthedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthedRoute,
} as any)
const onboardingLoginRoute = onboardingLoginRouteImport.update({
  id: '/(onboarding)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPolarRoute = ApiWebhookPolarRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCommunityPickRouteRoute =
  AuthedCommunityPickRouteRouteImport.update({
    id: '/community/pick',
    path: '/community/pick',
    getParentRoute: () => AuthedRoute,
  } as any)
const onboardingOnboardProfileRouteRoute =
  onboardingOnboardProfileRouteRouteImport.update({
    id: '/(onboarding)/onboard/profile',
    path: '/onboard/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const onboardingOnboardOrganizationRouteRoute =
  onboardingOnboardOrganizationRouteRouteImport.update({
    id: '/(onboarding)/onboard/organization',
    path: '/onboard/organization',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof onboardingLoginRoute
  '/test': typeof AuthedTestRoute
  '/onboard/organization': typeof onboardingOnboardOrganizationRouteRoute
  '/onboard/profile': typeof onboardingOnboardProfileRouteRoute
  '/community/pick': typeof AuthedCommunityPickRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof onboardingLoginRoute
  '/test': typeof AuthedTestRoute
  '/onboard/organization': typeof onboardingOnboardOrganizationRouteRoute
  '/onboard/profile': typeof onboardingOnboardProfileRouteRoute
  '/community/pick': typeof AuthedCommunityPickRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/(onboarding)/login': typeof onboardingLoginRoute
  '/_authed/test': typeof AuthedTestRoute
  '/(onboarding)/onboard/organization': typeof onboardingOnboardOrganizationRouteRoute
  '/(onboarding)/onboard/profile': typeof onboardingOnboardProfileRouteRoute
  '/_authed/community/pick': typeof AuthedCommunityPickRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/test'
    | '/onboard/organization'
    | '/onboard/profile'
    | '/community/pick'
    | '/api/auth/$'
    | '/api/webhook/polar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/test'
    | '/onboard/organization'
    | '/onboard/profile'
    | '/community/pick'
    | '/api/auth/$'
    | '/api/webhook/polar'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/(onboarding)/login'
    | '/_authed/test'
    | '/(onboarding)/onboard/organization'
    | '/(onboarding)/onboard/profile'
    | '/_authed/community/pick'
    | '/api/auth/$'
    | '/api/webhook/polar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  onboardingLoginRoute: typeof onboardingLoginRoute
  onboardingOnboardOrganizationRouteRoute: typeof onboardingOnboardOrganizationRouteRoute
  onboardingOnboardProfileRouteRoute: typeof onboardingOnboardProfileRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhookPolarRoute: typeof ApiWebhookPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/test': {
      id: '/_authed/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthedTestRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(onboarding)/login': {
      id: '/(onboarding)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof onboardingLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/community/pick': {
      id: '/_authed/community/pick'
      path: '/community/pick'
      fullPath: '/community/pick'
      preLoaderRoute: typeof AuthedCommunityPickRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(onboarding)/onboard/profile': {
      id: '/(onboarding)/onboard/profile'
      path: '/onboard/profile'
      fullPath: '/onboard/profile'
      preLoaderRoute: typeof onboardingOnboardProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/onboard/organization': {
      id: '/(onboarding)/onboard/organization'
      path: '/onboard/organization'
      fullPath: '/onboard/organization'
      preLoaderRoute: typeof onboardingOnboardOrganizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedTestRoute: typeof AuthedTestRoute
  AuthedCommunityPickRouteRoute: typeof AuthedCommunityPickRouteRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedTestRoute: AuthedTestRoute,
  AuthedCommunityPickRouteRoute: AuthedCommunityPickRouteRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  onboardingLoginRoute: onboardingLoginRoute,
  onboardingOnboardOrganizationRouteRoute:
    onboardingOnboardOrganizationRouteRoute,
  onboardingOnboardProfileRouteRoute: onboardingOnboardProfileRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhookPolarRoute: ApiWebhookPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
